### PR TITLE
validades input on focusOut instead of when user presses a key

### PR DESCRIPTION
**Pull request by thiagohersan**
Validating the input when user hits the ENTER key is very specific, and fails if, for example, the user hits the TAB key instead. This modification checks the input on focusOut instead. Just a suggestion.

### CODE REVIEW

**Comment by cheonhyangzhang** [comment]
@thiagohersan 
That's a good point.
After testing, actually I found a bug that if user input a duplicate tag, hit enter, error message is shown, but if user click somewhere else to make it unfocus, the duplicated tag is added.

So maybe we should always check whenever before we add a tag.
I don't know if user hits the ENTER will trigger focusOut of input. 
But maybe it' better to have a helper function to add a tag and inside of it, we always check if current tag we are trying to add is valid or not.

What's yours thoughts?

**Comment by thiagohersan** [comment]
You're right. Enter doesn't trigger focusOut.
Maybe a helper function that is used in both cases?

**Comment by cheonhyangzhang** [comment]
Yes. I think that's the better solution. I have created #15 to keep track of the validation issue.

**Comment by cheonhyangzhang** [comment]
@thiagohersan  
The changes in #15  are implemented in v1.2.4
https://github.com/cheonhyangzhang/paper-tags-input/releases/tag/v1.2.4

**Comment by cheonhyangzhang** [comment]
Features already implemented hence closing.

**Pull request closed without merging**
