### PR TITLE
Improve tag text position.

### PR DESCRIPTION
**Pull request by MacTheZazou**
The tag name is not centered. This look a bit weird.

### CODE REVIEW

**Comment by cheonhyangzhang** [comment]
Do you mean this?

**Comment by MacTheZazou** [comment]
No, just the text position in the large tags: 
capture d ecran 2016-11-30 a 16 13 03

(left after update)

Maybe I'll also debug the smaller tags after.

**Comment by cheonhyangzhang** [comment]
@MacTheZazou  Got it
Will look into it.

The smaller tags issue actually is a little strange. 
I noticed that in my local environment, it looks perfectly fine, but when I deploy to github io, it looks weird.

**Comment by cheonhyangzhang** [comment]
Code looks good and tested locally and it worked fine.

**Pull request merged**
